fs = require 'fs'
path = require 'path'
esprima = require 'esprima'


tokenizeJS= (original)->
  rawTokenized = esprima.tokenize(original)
  #rawTokenized = esprima.tokenize("    for (var i = 1; i <= totalNumberofRows; i++) {")
  #console.log "tokens tokens"
  #console.log rawTokenized
  cleverTokens = []
  i = 0
  while i < rawTokenized.length
    if (rawTokenized[i]['type'] == 'Boolean') | (rawTokenized[i]['type'] == 'Keyword') | (rawTokenized[i]['type'] == 'Punctuator')
      #console.log "value"
      cleverTokens.push(rawTokenized[i]['value'])
    else # Identifier Numeric String RegularExpression
        #there's plenty of relevant system Identifiers such as console log
        #there's some relevant user Identifiers such as i
        #there's a few relevant Numeric values such as 0 or 1
      cleverTokens.push(rawTokenized[i]['type'])
    i++
  #console.log "obj"
  #console.log cleverTokens
  cleverTokens = JSON.stringify(cleverTokens)
  #cleverTokens = JSON.stringify(rawTokenized)
  #console.log cleverTokens
  regexp = /","/gm
  #cleverTokens = cleverTokens.replace( regexp, "\" \"")
  cleverTokens = cleverTokens.replace( regexp, " ")
  regexp = /(^\["|"]$)/gm
  cleverTokens = cleverTokens.replace( regexp, "")
  return cleverTokens

JSsource = fs.readFileSync path.resolve(__dirname, 'compilation.js')
JSsource = JSsource.toString()
tokenized = tokenizeJS(JSsource)

console.log tokenized
fs.writeFile(path.resolve(__dirname, 'lets_feed.txt'), tokenized)

#console.log JSON.stringify(esprima.parse('var answer = 42'), null, 4)

# ---
# generated by js2coffee 2.2.0
